### ISSUE TITLE
No builds

### ISSUE THREAD

**Issue by johanneskoester** [conda-forge/r-openssl-feedstock#2]
@jakirkham do you have any idea why this feedstock is not being built?

**Comment by bgruening** [comment]
I think it is related to this: https://github.com/conda-forge/staged-recipes/pull/2857#issuecomment-298158090

**Comment by jdblischak** [comment]
Can this be closed now? The feedstock has been built:

https://anaconda.org/conda-forge/r-openssl/files

**Comment by jakirkham** [comment]
Yeah this can be closed. The feedstock was improperly converted due to a bug at `staged-recipes`. IIRC we fixed the bug and readded this feedstock, which fixed the issue. Hence builds have worked since. Think we just forgot to close this.
